/*
 * generated by Xtext
 */
package org.eclipse.jqvt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JQVTUiModule extends org.eclipse.jqvt.ui.AbstractJQVTUiModule {
	public JQVTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
