/*
 * generated by Xtext
 */
package org.eclipse.jqvt.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.jqvt.ui.internal.JQVTActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JQVTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JQVTActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JQVTActivator.getInstance().getInjector(JQVTActivator.ORG_ECLIPSE_JQVT_JQVT);
	}
	
}
