/*
* generated by Xtext
*/
package org.eclipse.jqvt.ui.contentassist;

import org.eclipse.jqvt.ui.contentassist.AbstractJQVTProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JQVTProposalProvider extends AbstractJQVTProposalProvider {

}
