/*
* generated by Xtext
*/
package org.eclipse.jqvt.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JQVTOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
